#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

# Set the theme
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
#if [ -x "$(command -v feh)" ]; then
#    feh --bg-fill --randomize $SCRIPTPATH/wallpapers/
#fi

# Boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

~/.fehbg &

# Launch conky with config
if [ -x "$(command -v conky)" ]; then
    killall conky
    $SCRIPTPATH/conky/conky_launch.sh &
fi

# Make backup and change alacritty config
ALACRITTYDIR=$HOME/.config/alacritty

if [ ! -d "$ALACRITTYDIR" ]; then
    mkdir -p $ALACRITTYDIR
fi

if [ -f "$ALACRITTYDIR/alacritty.yml" ]; then
    mv "$ALACRITTYDIR/alacritty.yml" "$ALACRITTYDIR/alacritty.yml.old"
fi

cp "$SCRIPTPATH/alacritty/alacritty.yml" $ALACRITTYDIR

$SCRIPTPATH/scripts/dual-mon.sh &

# Boot polybar
if [ -x "$(command -v polybar)" ]; then
  $SCRIPTPATH/polybar/launch.sh
  exit 0
fi
